import type { EntityFormStep } from "@/features/admin/components/forms/entity-form-wizard"
import type { ProjectFormValues } from "@/features/admin/lib/schemas"

export const PROJECT_FORM_STEPS: EntityFormStep<keyof ProjectFormValues>[] = [
  {
    id: "basics",
    title: "Basics",
    description: "Title, slug, summary, and listing metadata.",
    fields: [
      "title",
      "slug",
      "summary",
      "tagline",
      "status",
      "year",
      "category",
      "role",
      "tech_stack",
    ],
  },
  {
    id: "media",
    title: "Media & links",
    description: "Cover images, demo video, and external URLs.",
    fields: [
      "icon_name",
      "cover_image",
      "thumbnail",
      "architecture_image",
      "demo_video_url",
      "project_url",
      "github_url",
    ],
  },
  {
    id: "story",
    title: "Story",
    description: "Hover preview, case study narrative, and approach.",
    fields: [
      "challenge",
      "solution",
      "impact",
      "overview",
      "problem",
      "why_built",
      "metrics",
      "approach",
      "my_contribution",
    ],
  },
  {
    id: "architecture",
    title: "Architecture",
    description: "System diagrams, tech stack, challenges, and tradeoffs.",
    fields: [
      "ai_design_nodes",
      "ai_design_edges",
      "architecture_nodes",
      "architecture_edges",
      "tech_stack_groups",
      "challenges",
      "tradeoffs",
    ],
  },
  {
    id: "outcomes",
    title: "Outcomes",
    description: "Results, learnings, timeline, and gallery.",
    fields: ["results", "learnings", "timeline", "gallery"],
  },
  {
    id: "publish",
    title: "Publish",
    description: "Knowledge graph, display settings, and rich content.",
    fields: [
      "ai_summary",
      "key_takeaways",
      "expertise_slugs",
      "concepts",
      "technologies",
      "project_facts",
      "faq",
      "featured",
      "display_order",
      "hover_preview_enabled",
      "content",
    ],
  },
]
